spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.202.21:3306/MyBlog?serverTimezone=GMT
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    use-generated-keys: true

server:
  port: 8081
