package life.daguo.boot.Pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.nickname
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.email
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.content
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.avatar
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.createTime
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.blog_id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    private Integer blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.parent_comment_id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    private Integer parentCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.admin_comment
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    private Boolean adminComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.create_time
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    private Date createTime;

    @Override
    public String toString() {
        return "comment{" +
                "id=" + id +
                ", nickname='" + nickname + '\'' +
                ", email='" + email + '\'' +
                ", content='" + content + '\'' +
                ", avatar='" + avatar + '\'' +
                ", createtime=" + createtime +
                ", blogId=" + blogId +
                ", parentCommentId=" + parentCommentId +
                ", adminComment=" + adminComment +
                ", createTime=" + createTime +
                ", blog=" + blog +
                ", replyComments=" + replyComments +
                ", parentComment=" + parentComment +
                '}';
    }

    public life.daguo.boot.Pojo.blog getBlog() {
        return blog;
    }

    public void setBlog(life.daguo.boot.Pojo.blog blog) {
        this.blog = blog;
    }

    private blog blog;

    public List<comment> getReplyComments() {
        return replyComments;
    }

    public void setReplyComments(List<comment> replyComments) {
        this.replyComments = replyComments;
    }

    public comment getParentComment() {
        return parentComment;
    }

    public void setParentComment(comment parentComment) {
        this.parentComment = parentComment;
    }

    private List<comment> replyComments = new ArrayList<>();
    private comment parentComment;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.id
     *
     * @return the value of t_comment.id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.id
     *
     * @param id the value for t_comment.id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.nickname
     *
     * @return the value of t_comment.nickname
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.nickname
     *
     * @param nickname the value for t_comment.nickname
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.email
     *
     * @return the value of t_comment.email
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.email
     *
     * @param email the value for t_comment.email
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.content
     *
     * @return the value of t_comment.content
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.content
     *
     * @param content the value for t_comment.content
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.avatar
     *
     * @return the value of t_comment.avatar
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.avatar
     *
     * @param avatar the value for t_comment.avatar
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.createTime
     *
     * @return the value of t_comment.createTime
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.createTime
     *
     * @param createtime the value for t_comment.createTime
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.blog_id
     *
     * @return the value of t_comment.blog_id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.blog_id
     *
     * @param blogId the value for t_comment.blog_id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.parent_comment_id
     *
     * @return the value of t_comment.parent_comment_id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public Integer getParentCommentId() {
        return parentCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.parent_comment_id
     *
     * @param parentCommentId the value for t_comment.parent_comment_id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public void setParentCommentId(Integer parentCommentId) {
        this.parentCommentId = parentCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.admin_comment
     *
     * @return the value of t_comment.admin_comment
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public Boolean getAdminComment() {
        return adminComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.admin_comment
     *
     * @param adminComment the value for t_comment.admin_comment
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public void setAdminComment(Boolean adminComment) {
        this.adminComment = adminComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.create_time
     *
     * @return the value of t_comment.create_time
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.create_time
     *
     * @param createTime the value for t_comment.create_time
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}