package life.daguo.boot.Pojo;

public class tblogtags {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tags.blogs_id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    private Integer blogsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog_tags.tags_id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    private Integer tagsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_tags.blogs_id
     *
     * @return the value of t_blog_tags.blogs_id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public Integer getBlogsId() {
        return blogsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_tags.blogs_id
     *
     * @param blogsId the value for t_blog_tags.blogs_id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public void setBlogsId(Integer blogsId) {
        this.blogsId = blogsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog_tags.tags_id
     *
     * @return the value of t_blog_tags.tags_id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public Integer getTagsId() {
        return tagsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog_tags.tags_id
     *
     * @param tagsId the value for t_blog_tags.tags_id
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    public void setTagsId(Integer tagsId) {
        this.tagsId = tagsId;
    }

    @Override
    public String toString() {
        return "tblogtags{" +
                "blogsId=" + blogsId +
                ", tagsId=" + tagsId +
                '}';
    }
}