package life.daguo.boot.Dao;

import java.util.List;

import com.github.pagehelper.PageInfo;
import life.daguo.boot.Pojo.tag;
import life.daguo.boot.Pojo.tagExample;
import org.apache.ibatis.annotations.Param;

public interface tagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int countByExample(tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int deleteByExample(tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int insert(tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int insertSelective(tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    List<tag> selectByExample(tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    tag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") tag record, @Param("example") tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int updateByExample(@Param("record") tag record, @Param("example") tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int updateByPrimaryKeySelective(tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int updateByPrimaryKey(tag record);
    List<tag> findTop(PageInfo<tag> page);
}