package life.daguo.boot.Dao;

import java.util.List;
import life.daguo.boot.Pojo.tblogtags;
import life.daguo.boot.Pojo.tblogtagsExample;
import org.apache.ibatis.annotations.Param;

public interface tblogtagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int countByExample(tblogtagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int deleteByExample(tblogtagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int insert(tblogtags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int insertSelective(tblogtags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    List<tblogtags> selectByExample(tblogtagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") tblogtags record, @Param("example") tblogtagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blog_tags
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int updateByExample(@Param("record") tblogtags record, @Param("example") tblogtagsExample example);
}