package life.daguo.boot.Dao;

import java.util.List;

import com.github.pagehelper.PageInfo;
import life.daguo.boot.Pojo.type;
import life.daguo.boot.Pojo.typeExample;
import org.apache.ibatis.annotations.Param;

public interface typeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int countByExample(typeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int deleteByExample(typeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int insert(type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int insertSelective(type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    List<type> selectByExample(typeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    type selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") type record, @Param("example") typeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int updateByExample(@Param("record") type record, @Param("example") typeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int updateByPrimaryKeySelective(type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Mon May 31 15:02:22 CST 2021
     */
    int updateByPrimaryKey(type record);

    List<type> findTop(PageInfo<type> page);
}